---
title: "Bayes Net Example - Happiness"
author: "Julia Fischer"
date: "2023-09-18"
output:
  rmdformats::robobook:
    highlight: tango
  html_document:
    toc: true
    toc_depth: 4
    code_download: true
  word_document: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

Specifying a simple Bayesian network for demonstrative purposes; note that the probabilities were chosen by hand, as opposed to being generated by data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bnlearn)
library(Rgraphviz)
```

```{r specify bn}
sleep <- matrix(c(0.7, 0.3), ncol = 2, dimnames = list(NULL, c("True", "False")))
sleep

happy <- c(0.8, 0.2, 0.4, 0.6)
dim(happy) = c(2, 2)
dimnames(happy) = list("Happy" = c("True", "False"), "Sleep" = c("True", "False"))
happy

donate <- c(0.5, 0.5, 0.1, 0.9)
dim(donate) = c(2, 2)
dimnames(donate) = list("Donate" = c("True", "False"), "Happy" = c("True", "False"))
donate

volunteer <- c(0.6, 0.4, 0.2, 0.8)
dim(volunteer) = c(2, 2)
dimnames(volunteer) = list("Volunteer" = c("True", "False"), "Happy" = c("True", "False"))
volunteer
```

```{r fit bn}
#bn_structure <- model2network("[A][B|A][C|B][D|B]")
bn_structure <- model2network("[Sleep][Happy|Sleep][Donate|Happy][Volunteer|Happy]")
bn_fit = custom.fit(bn_structure, dist = list(Sleep = sleep, Happy = happy, Donate = donate, Volunteer = volunteer))
bn_fit
```

```{r plot bn}
col_1 <- c("Sleep", "Happy", "Happy")
col_2 <- c("Happy", "Donate", "Volunteer")
arc_matrix <- cbind(col_1, col_2)
graphviz.plot(bn_fit, highlight = c(list(nodes = c("Sleep", "Happy", "Donate", "Volunteer"), arcs = arc_matrix, col = "black", fill = "lightgreen", lwd = 1.5)))
```